<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:suncorp-com-au:schema:enterprise:getaddress:2012:05"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http"
	name="ServiceBBBEndpointService" targetNamespace="urn:suncorp-com-au:schema:enterprise:getaddress:2012:05">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns:tns="urn:suncorp-com-au:schema:enterprise:getaddress:2012:05"
			attributeFormDefault="unqualified" elementFormDefault="unqualified"
			targetNamespace="urn:suncorp-com-au:schema:enterprise:getaddress:2012:05">
			<xsd:element name="GetAddressRequest" type="tns:GetAddressRequest" />
			<xsd:complexType name="GetAddressRequest">
				<xsd:sequence>
					<xsd:element minOccurs="0" name="GetAddressCriteria"
						type="xsd:string" />
				</xsd:sequence>
			</xsd:complexType>
			<xsd:element name="GetAddressRequestResponse" type="tns:GetAddressRequestResponse" />
			<xsd:complexType name="GetAddressRequestResponse">
				<xsd:sequence>
					<xsd:element minOccurs="0" name="return" type="xsd:string" />
				</xsd:sequence>
			</xsd:complexType>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="GetAddressRequest">
		<wsdl:part element="tns:GetAddressRequest" name="parameters">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="GetAddressRequestResponse">
		<wsdl:part element="tns:GetAddressRequestResponse" name="parameters">
		</wsdl:part>
	</wsdl:message>
	<wsdl:portType name="ServiceBBBEndpoint">
		<wsdl:operation name="GetAddressRequest">
			<wsdl:input message="tns:GetAddressRequest" name="GetAddressRequest">
			</wsdl:input>
			<wsdl:output message="tns:GetAddressRequestResponse"
				name="GetAddressRequestResponse">
			</wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ServiceBBBEndpointServiceSoapBinding"
		type="tns:ServiceBBBEndpoint">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="GetAddressRequest">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="GetAddressRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="GetAddressRequestResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ServiceBBBEndpointService">
		<wsdl:port binding="tns:ServiceBBBEndpointServiceSoapBinding"
			name="ServiceBBBEndpointPort">
			<soap:address location="http://localhost:8187/BBB" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>